version: 2

sources :
    - name: jaffle_shop
      database: raw
      schema: jaffle_shop
      tables : 
        - name: customers
          description: one record per customer
        - name: orders  