version: 2

sources :
    - name: jaffle_shop
      database: raw
      schema: jaffle_shop
      config:
        freshness: 
          error_after:
            count: 3
            period: day
          warn_after:
            count: 3
            period: day
      
      tables : 
        - name: customers
          description: one record per customer
          config:
            freshness:
        - name: orders  
          